apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee
        image: 10.128.0.17:5000/syedhajirali/employee-service:${BUILD_NUMBER}   
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-service
              key: database-name
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
      - name: mysql-service
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-service
              key: database-name
        - name: MYSQL_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-user
        - name: MYSQL_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-password      
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-service
  name: employee-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employee-service
  sessionAffinity: None
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql-service
  sessionAffinity: None
  type: ClusterIP
  
---
 
apiVersion: v1
kind: Secret
metadata:
  name: mysql-service
data:
  rootPassword: cGFzc3dvcmQ=
  database-user: ZGJ1c2Vy
  database-password: ZGJwYXNz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-service
data:
  database-name: microservices  
  
