apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-name
data:
  mysqldb.properties: |
    mysql.dbname=sampledb
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username.properties: bXlzcWwudXNlcj1teXNxbAo=
  password.properties: bXlzcWwucGFzc3dvcmQ9cGFzc3dvcmQK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      volumes:
      - name: mysqlcm
        configMap:
          name: mysql-db-name
      - name: mysqlse
        secret:
          secretName: mysql-secret
      containers:
      - name: employee-service
        image: 10.128.0.17:5000/syedhajirali/employee-service:${BUILD_NUMBER}  
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: mysqlcm
          mountPath: /etc/config
        - name: mysqlse
          mountPath: /etc/vol-secrets
      imagePullSecrets:
      - name: acr-registry
---
kind: Service
apiVersion: v1
metadata:
  name: employee-service
spec:
  type: NodePort
  selector:
    app: employee-service
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-service
type: Opaque
data:
  database-name: c2FtcGxlZGI=
  database-password: cGFzc3dvcmQ=
  database-root-password: cGFzc3dvcmQ=
  database-user: bXlzcWw=
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-service
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
  labels:
    app: mysql-ephemeral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
      - name: mysql-service
        image: mysql/mysql-server:5.7.22
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-password
        - name: MYSQL_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-service
              key: database-name
