apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-name
data:
  mysqldb.properties: |
    mysql.dbname=sampledb
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username.properties: bXlzcWwudXNlcj1teXNxbAo=
  password.properties: bXlzcWwucGFzc3dvcmQ9cGFzc3dvcmQK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      volumes:
      - name: mysqlcm
        configMap:
          name: mysql-db-name
      - name: mysqlse
        secret:
          secretName: mysql-secret
      containers:
      - name: po-service
        image: 10.128.0.17:5000/syedhajirali/employee-service:${BUILD_NUMBER}  
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: mysqlcm
          mountPath: /etc/config
        - name: mysqlse
          mountPath: /etc/vol-secrets
      imagePullSecrets:
      - name: acr-registry
---
kind: Service
apiVersion: v1
metadata:
  name: po-service
spec:
  type: LoadBalancer
  selector:
    app: po-service
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 8080
