apiVersion: v1
kind: Pod
metadata:
  name: test-reg
  labels:
    type: test-reg
spec:
  containers:
  - name: private-reg-container
    image:  10.128.0.12:5000/syedhajirali/employee:${BUILD_NUMBER}
  imagePullSecrets:
  - name: regcred
